name: "Project 2 deployment"
on: push
jobs:
  linting:
    runs-on : "ubuntu-latest"
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        uses: npm ci
      - name: Run linting
        uses: npm run lint
  Testing:
    needs: linting
    runs-on: "ubuntu-latest"
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        uses: npm ci
      - name: Run test command
        uses: npm run test
  Deployment:
    needs: testing
    runs-on: "ubuntu-latest"
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        uses: npm ci
      - name: Run deployment
        uses: npm run build
